# Generated by Django 5.2.8 on 2026-02-28 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='en_solde',
            field=models.BooleanField(default=False, verbose_name='En solde (badge SOLDE)'),
        ),
        migrations.AddField(
            model_name='produit',
            name='est_nouveau',
            field=models.BooleanField(default=False, verbose_name='Nouveau (badge NEW)'),
        ),
    ]
