# Generated by Django 6.0.3 on 2026-03-05 20:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_add_est_nouveau_en_solde'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=255, verbose_name='Nom complet')),
                ('email', models.EmailField(max_length=254, verbose_name='Email de contact')),
                ('telephone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('adresse', models.TextField(verbose_name='Adresse de livraison')),
                ('ville', models.CharField(default='Abidjan', max_length=100, verbose_name='Ville')),
                ('total_price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant Total (FCFA)')),
                ('payment_method', models.CharField(choices=[('GENIUSPAY', 'GeniusPay (Wave, Orange, MTN, Moov)'), ('WHATSAPP', 'Commande WhatsApp (Paiement manuel)'), ('PAYPAL', 'PayPal')], default='WHATSAPP', max_length=20, verbose_name='Mode de paiement')),
                ('status', models.CharField(choices=[('PENDING', 'En attente de paiement'), ('PAID', 'Payée'), ('PROCESSING', 'En cours de préparation'), ('SHIPPED', 'Expédiée'), ('DELIVERED', 'Livrée'), ('CANCELLED', 'Annulée')], default='PENDING', max_length=20, verbose_name='Statut')),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID Transaction')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Payée')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de paiement')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date Création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mise à jour')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Bon de Commande',
                'verbose_name_plural': 'Bons de Commande',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantité')),
                ('price', models.IntegerField(verbose_name='Prix unitaire saisi')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.order', verbose_name='Commande')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.produit', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Article commandé',
                'verbose_name_plural': 'Articles commandés',
            },
        ),
    ]
